# Mongoid Configuration
# =====================
#
# Copy this file to config/mongoid.yml and
# modify it accordingly. This file will automatically
# be copied to shared/config on the server when
# `cap deploy:setup` is ran the first time. Be sure
# to place production specific settings there

defaults: &defaults
  host: localhost
  identity_map_enabled: true

  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: errbit_development

test:
  <<: *defaults
  database: errbit_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: localhost
  port: 27017
  username: 
  password: 
  database: errbit_production
